// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCeL0O601KB6riUwcfkC_PoG8O0TF2uyrM',
    appId: '1:561427609705:web:51b30d54ef3ef5a0238af8',
    messagingSenderId: '561427609705',
    projectId: 'fir-flutter-codelab-2cb02',
    authDomain: 'fir-flutter-codelab-2cb02.firebaseapp.com',
    storageBucket: 'fir-flutter-codelab-2cb02.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCBrgtuRSQGi-JQOa5CQbKsnxYINy_ieYg',
    appId: '1:561427609705:android:108099ab60f9c541238af8',
    messagingSenderId: '561427609705',
    projectId: 'fir-flutter-codelab-2cb02',
    storageBucket: 'fir-flutter-codelab-2cb02.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAWIdC2ltkeqcMPzVMULmCXoDneUqhJB4o',
    appId: '1:561427609705:ios:e604dddcba1cd654238af8',
    messagingSenderId: '561427609705',
    projectId: 'fir-flutter-codelab-2cb02',
    storageBucket: 'fir-flutter-codelab-2cb02.appspot.com',
    iosClientId: '561427609705-98bfougsj41lgdvnuiide09osajtugto.apps.googleusercontent.com',
    iosBundleId: 'com.example.firerbaseFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAWIdC2ltkeqcMPzVMULmCXoDneUqhJB4o',
    appId: '1:561427609705:ios:e604dddcba1cd654238af8',
    messagingSenderId: '561427609705',
    projectId: 'fir-flutter-codelab-2cb02',
    storageBucket: 'fir-flutter-codelab-2cb02.appspot.com',
    iosClientId: '561427609705-98bfougsj41lgdvnuiide09osajtugto.apps.googleusercontent.com',
    iosBundleId: 'com.example.firerbaseFlutter',
  );
}
